name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'Poster-WPF/Poster-WPF.csproj'

env:
  Name: Poster-WPF
  Solution_Name: Poster-WPF.sln
  Project_Name: Poster-WPF\Poster-WPF.csproj

jobs:
  pre-release:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true

    - name: Get previous version
      id: previous_version
      run: |
        $prev_version = git describe --tags $(git rev-list --tags --max-count=1)
        Write-Output Previous Version: $prev_version
        Write-Output "prev_version=$prev_version" >> $env:GITHUB_OUTPUT

    - name: Get version
      id: version
      run: |
        Invoke-WebRequest https://github.com/BrandonStudio/GitHubActionScripts/raw/main/getMSBuildApplicationVersion.py -OutFile getVersion.py
        $version = python getVersion.py ${{ env.Project_Name }}
        $version = "v" + $version
        Write-Output Current Version: $version
        Write-Output "version=$version" >> $env:GITHUB_OUTPUT

  release:
    runs-on: windows-latest
    needs: pre-release
    if: needs.pre-release.outputs.prev_version != needs.pre-release.outputs.version
    env:
      CURRENT_VERSION: ${{ needs.pre-release.outputs.version }}

    steps:
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build
      run: msbuild /p:Configuration=Release ${{ env.Project_Name }}

    - name: Create release
      id: create_release
      uses: BrandonStudio/tag-and-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.CURRENT_VERSION }}
        release_name: Release ${{ env.CURRENT_VERSION }}
        draft: true
        prerelease: false
        body: |
          # Changes
        discussion_category_name: 'Announcements'
        generate_release_notes: true

    - name: Trim url
      id: trim_url
      run: |
        $url = "${{ steps.create_release.outputs.upload_url }}"
        $url = [regex]::Replace($url, "assets(?!.*assets).*", "assets?name")
        Write-Output "upload_url=$url" >> $env:GITHUB_OUTPUT

    - name: Upload pdb
      run: >
        Invoke-WebRequest -Method Post ${{ steps.trim_url.outputs.upload_url }}=${{ env.Name }}-${{ env.CURRENT_VERSION }}.pdb
        -Headers @{ "Authorization"="token ${{ secrets.GITHUB_TOKEN }}"; "Content-Type"="application/octet-stream" }
        -InFile Poster-WPF\bin\Release\${{ env.Name }}.pdb

    - name: Package and upload other assets
      env:
        ARCHIVE_NAME: ${{ env.Name }}-${{ env.CURRENT_VERSION }}-portable.zip
        UPLOAD_URL: ${{ steps.trim_url.outputs.upload_url }}
      run: |
        Set-Location Poster-WPF\bin\Release
        Remove-Item ${{ env.Name }}.pdb
        Remove-Item ${{ env.Name }}.application
        Remove-Item app.publish -Recurse
        Compress-Archive -Path * -DestinationPath ..\${{ env.ARCHIVE_NAME }}
        Invoke-WebRequest -Method Post ${{ env.UPLOAD_URL }}=${{ env.ARCHIVE_NAME }} `
        -Headers @{ "Authorization"="token ${{ secrets.GITHUB_TOKEN }}"; "Content-Type"="application/octet-stream" } `
        -InFile ..\${{ env.ARCHIVE_NAME }}
